template = ""
rev_id = 4
template_sha = "87be02986858c4b7ae5e8613b6f951c3c209b221"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "smn"
__UND2C_TRG__ = "se"
__UNDEFINED_SOURCE__ = "Inari Saami"
__UNDEFINED_TARGET__ = "North Saami"
__UND_SRC__ = "smn"
__UND_TRG__ = "sme"
